### ISSUE TITLE
how to install r2lang? getting have_rlang=False

### ISSUE THREAD

**Issue by Linuxinet** [radareorg/r2ai#17]
https://github.com/radareorg/r2ai/blob/86a5c2bebfe52f877c1d5767d95f1e07df59a9e1/main.py#L42 it tries to `import r2lang` but it failed,

for r2pipe it was fixed with pip install r2pipe, but I didn't found any way to install r2lang

<img width="1792" alt="Screenshot 2024-03-28 at 9 34 09 PM" src="https://github.com/radareorg/r2ai/assets/55936553/13a342fc-3f06-42dd-8dd8-25c4ad673c34">

**Comment by trufae** [comment]
r2lang is provided by r2pm -ci rlang-python

**Comment by Linuxinet** [comment]
got it, when i run r2, it was imported there.

but when we load r2ai repl with `#!pipe python3 main.py`

in repl.py it was not importing the r2lang

for debug, I added print logs

<img width="1792" alt="Screenshot 2024-03-28 at 10 25 17 PM" src="https://github.com/radareorg/r2ai/assets/55936553/e044c8aa-426c-490b-8bba-5403e375830f">


and one more thing, I was not able to run r2 commands in r2ai repl with `:`

<img width="282" alt="Screenshot 2024-03-28 at 10 30 56 PM" src="https://github.com/radareorg/r2ai/assets/55936553/a3a54276-b0a4-4144-8a22-f7133c750bb9">

https://github.com/radareorg/r2ai/blob/d80451e8a3fefdfcfdf80a1dc9ff1e21c71d7c7c/r2ai/repl.py#L306

r2 set to None and not updated
https://github.com/radareorg/r2ai/blob/d80451e8a3fefdfcfdf80a1dc9ff1e21c71d7c7c/r2ai/repl.py#L18

**Comment by trufae** [comment]
fixed in master :) please confirm and thanks for reporting!

**Comment by Linuxinet** [comment]
Awesome, the issue is fixed.

<img width="626" alt="Screenshot 2024-03-29 at 2 09 29 AM" src="https://github.com/radareorg/r2ai/assets/55936553/037e46d3-4e91-4109-ba5e-2f609732edc0">

**Comment by trufae** [comment]
Ok to close now?
