### ISSUE TITLE
How do you feel about adding recursive tool calling like r2d2?

### ISSUE THREAD

**Issue by dnakov** [radareorg/r2ai#2]
I'm thinking of merging efforts here but I'm not sure if this is something you want r2ai to be able to do or not.
I could start messing around with it, love the support of all the models.
Maybe some other mode maybe like `auto`:
```
r2ai :auto solve this crackme
```
It may be challenging to support tool calling for all models, but a decent amount would work.
Let me know what you think
Thanks!

**Comment by trufae** [comment]
That would be really cool, and i think that being able to have automatic modes like the one you did in r2d2, using local models with vectordb to extend the knowledge about r2 commands could work quite well. Would you like to implement this feature?

**Comment by dnakov** [comment]
Awesome, yeah, I'll give it a shot!
