### ISSUE TITLE
decai: syntax error

### ISSUE THREAD

**Issue by prodrigestivill** [radareorg/r2ai#96]
Using:
```
radare2 5.9.8 0 @ linux-x86-64
birth: git.5.9.8 2024-12-10__22:51:48
commit: 5.9.8
options: gpl release -O1 cs:5 cl:0 make
r2ai decai: 0.8.8
```

It looks like at least when in use inside flatpak and snap radare2 builds, it fails to load the r2ai decai plugin with this error:
```
ERROR: SyntaxError: unexpected end of string
ERROR:     at -:467:17

ERROR: [uninitialized]
```

It references to [this line](https://github.com/radareorg/r2ai/blob/0.8.8/decai/decai.r2.js#L467).

**Comment by trufae** [comment]
Fixed

**Comment by trufae** [comment]
In 0.9.0
